# Generated by Django 5.2.1 on 2025-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='reviw_game',
            new_name='review_game',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='reviw_game_html',
            new_name='review_game_html',
        ),
        migrations.AlterField(
            model_name='game',
            name='end_game',
            field=models.CharField(max_length=5),
        ),
    ]
